services:
  portfolio:
    image: nginx:latest
    container_name: 'nurulhudaapon.com'
    volumes:
      - ./out:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
    name: proxy_network
